/**
 * Central Express error-handling middleware.
 *
 * All errors generated by controllers, services and middleware
 * eventually reach this function. Centralising error handling
 * provides consistent API responses and prevents internal
 * implementation details from leaking to clients.
 *
 * Express identifies an error handler by its four arguments:
 * error, req, res and next.
 */
function errorHandler(error, req, res, next) {
    /*
     * Use the status code supplied by an expected application
     * error. Unexpected errors default to HTTP 500.
     */
    const statusCode = error.statusCode || 500;

    /*
     * Do not expose internal exception details to clients when
     * running in production.
     */
    const message =
        statusCode === 500 && process.env.NODE_ENV === 'production'
            ? 'An unexpected server error occurred.'
            : error.message;

    /*
     * Log unexpected server errors for operational diagnosis.
     * A production implementation could forward these logs to
     * an external observability platform.
     */
    if (statusCode >= 500) {
        console.error({
            message: error.message,
            stack: error.stack,
            method: req.method,
            path: req.originalUrl,
            timestamp: new Date().toISOString(),
        });
    }

    const response = {
        status: 'error',
        message,
    };

    /*
     * Stack traces are useful during development but represent
     * unnecessary information disclosure in production.
     */
    if (process.env.NODE_ENV !== 'production') {
        response.stack = error.stack;
    }

    res.status(statusCode).json(response);
}

module.exports = errorHandler;
